/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    Integrations: typeof import('./../components/Integrations.vue')['default']
    IntegrationSync: typeof import('./../components/IntegrationSync.vue')['default']
    IntegrationTable: typeof import('./../components/IntegrationTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sync: typeof import('./../components/Sync.vue')['default']
    SyncPoc: typeof import('./../components/SyncPoc.vue')['default']
    Tag: typeof import('primevue/tag')['default']
  }
}
